// <auto-generated />
using System;
using Ecomm_2012500811.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecomm_2012500811.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecomm_2012500811.Shared.Kategori", b =>
                {
                    b.Property<int>("IdKategori")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategori"));

                    b.Property<string>("NamaKategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKategori");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            IdKategori = 1,
                            NamaKategori = "Sneakers"
                        },
                        new
                        {
                            IdKategori = 2,
                            NamaKategori = "Sport"
                        });
                });

            modelBuilder.Entity("Ecomm_2012500811.Shared.Produk", b =>
                {
                    b.Property<int>("IdProduk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduk"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeskripsiProduk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GambarProduk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HargaOriginalProduk")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("HargaProduk")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("IdKategori")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduk");

                    b.HasIndex("IdKategori");

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            IdProduk = 1,
                            DateCreated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2677),
                            DateUpdated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2697),
                            DeskripsiProduk = "Sepatu Adidas Ukuran 38-43",
                            GambarProduk = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTISLcBhlpqPMC1iE-qIBVWED3REW0qfK2pA_dXB_3yG3vEQFXZ8afMmsvMG1zvHbbJp1g&usqp=CAU",
                            HargaOriginalProduk = 199.000m,
                            HargaProduk = 149.000m,
                            IdKategori = 1,
                            IsDelete = false,
                            IsPublic = true,
                            NamaProduk = "Sepatu Adidas"
                        },
                        new
                        {
                            IdProduk = 2,
                            DateCreated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2705),
                            DateUpdated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2706),
                            DeskripsiProduk = "Sepatu Nike Ukuran 38-43",
                            GambarProduk = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq6RTSQnR_qiByUu3iH8e20oGUecnUIQxC_G9fj-OLEaKzHawsmho2wbKzC98Q88JTFLE&usqp=CAU",
                            HargaOriginalProduk = 999.000m,
                            HargaProduk = 949.000m,
                            IdKategori = 1,
                            IsDelete = false,
                            IsPublic = true,
                            NamaProduk = "Sepatu Nike"
                        },
                        new
                        {
                            IdProduk = 3,
                            DateCreated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2709),
                            DateUpdated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2710),
                            DeskripsiProduk = "Sepatu Ventella Ukuran 38-43",
                            GambarProduk = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTePc6kARywUKCvpom7b7zNqsvSdCKjGXCd1zANjS2HTXXSxqlzWMDEiqol0Oebz9ZrBFc&usqp=CAU",
                            HargaOriginalProduk = 399.000m,
                            HargaProduk = 349.000m,
                            IdKategori = 1,
                            IsDelete = false,
                            IsPublic = true,
                            NamaProduk = "Sepatu Ventella"
                        },
                        new
                        {
                            IdProduk = 4,
                            DateCreated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2714),
                            DateUpdated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2715),
                            DeskripsiProduk = "Sepatu Jordan Ukuran 38-43",
                            GambarProduk = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv7AoizoHCEmgByOHokrFFAIkPrb5SXUH3ElgQprRtsSzKMLi_O4Dx8DlmIrE-QiVtnPk&usqp=CAU",
                            HargaOriginalProduk = 499.000m,
                            HargaProduk = 449.000m,
                            IdKategori = 2,
                            IsDelete = false,
                            IsPublic = true,
                            NamaProduk = "Sepatu Jordan"
                        },
                        new
                        {
                            IdProduk = 5,
                            DateCreated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2717),
                            DateUpdated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2718),
                            DeskripsiProduk = "Sepatu Vans Ukuran 38-43",
                            GambarProduk = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYijF-XI6xk7kadZc3UxFfy37-JkdQbIjkGPLMAlPC3_33zUwX7_i3ZVEMXuN6Grw9G2o&usqp=CAU",
                            HargaOriginalProduk = 149.000m,
                            HargaProduk = 99.000m,
                            IdKategori = 2,
                            IsDelete = false,
                            IsPublic = true,
                            NamaProduk = "Sepatu Vans"
                        },
                        new
                        {
                            IdProduk = 6,
                            DateCreated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2721),
                            DateUpdated = new DateTime(2023, 7, 10, 20, 56, 50, 13, DateTimeKind.Local).AddTicks(2722),
                            DeskripsiProduk = "Sepatu Mizuno High Ukuran 40-43",
                            GambarProduk = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReTaGHZ7Wmq5JErl_uv0qOWggHbMgjRJEv8bvu0TjyXS4lJJKmZavjr5vdQT-eiYA-EBQ&usqp=CAU",
                            HargaOriginalProduk = 699.000m,
                            HargaProduk = 649.000m,
                            IdKategori = 2,
                            IsDelete = false,
                            IsPublic = true,
                            NamaProduk = "Sepatu Mizuno"
                        });
                });

            modelBuilder.Entity("Ecomm_2012500811.Shared.Varian", b =>
                {
                    b.Property<int>("IdVarian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVarian"));

                    b.Property<string>("NamaVarian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVarian");

                    b.ToTable("Varian");
                });

            modelBuilder.Entity("Ecomm_2012500811.Shared.Produk", b =>
                {
                    b.HasOne("Ecomm_2012500811.Shared.Kategori", "Kategori")
                        .WithMany("Produk")
                        .HasForeignKey("IdKategori")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Ecomm_2012500811.Shared.Kategori", b =>
                {
                    b.Navigation("Produk");
                });
#pragma warning restore 612, 618
        }
    }
}
